### ISSUE TITLE
Imager::Screenshot module related problem

### ISSUE THREAD

**Issue by ourlord** [kaikaizi/screen-capture#1]
Get this error when running the script. Running on ubuntu12. And already ran `sudo apt-get install libimager-perl` to install necessary modules for perl (or actually this was not the right one?).

```
 Can't locate Imager/Screenshot.pm in @INC (you may need to install the Imager::Screenshot module) (@INC contains: /home/lawliet/.perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at ./screen_cap.pl line 3.
 BEGIN failed--compilation aborted at ./screen_cap.pl line 3.
```

**Comment by kaikaizi** [comment]
Hi,

I don't have Ubuntu unfortunately. The error you ran into is due to Perl not finding your Imager::Screenshot module in your PERL5LIB env path. I installed this module from CPAN by running `cpan -i Imager::Screenshot' (you need to configure CPAN if you did not do this before).

Double check that $HOME/.perl5/lib/perl5 (or wherever CPAN gets installed) is in your $PERL5LIB. It should carp:

Usage: screen_cap.pl left right top bottom at screen_cap.pl line 43.

when you run `perl screen_cap.pl'.
